### ISSUE TITLE
Prevent OpenType utility classes overwriting each other

### ISSUE THREAD

**Issue by RoelN** [clagnut/TODS#1]
Currently the following wouldn't work:

```html
<div class="tnum zero">0123</div>
```

As the latter would overwrite the former:

```css
.tnum { font-variant-numeric: tabular-nums; }
.zero { font-variant-numeric: slashed-zero; }
```

**Comment by clagnut** [comment]
Ah. You're right. I thought they would build upon each other, not overwrite each other. How annoying. Don't really want to go down the route of CSS custom properties for this too. Maybe just make it clear that one utility would overwrite the other if used together?

**Comment by clagnut** [comment]
Because the same will apply to other `font-variant-*` properties.

**Comment by RoelN** [comment]
The alternative _could_ be to account for all combinations...

```css
.tnum { font-variant-numeric: tabular-nums; }
.zero { font-variant-numeric: slashed-zero; }

**Comment by RoelN** [comment]
An alternative could be to account for all combinations...

```css
.tnum { font-variant-numeric: tabular-nums; }
.zero { font-variant-numeric: slashed-zero; }
.tnum.zero { font-variant-numeric: tabular-nums slashed-zero; }
```

**Comment by clagnut** [comment]
or maybe. seeing as I'm using classes anyway, I can set up custom properties for the possible values within each `font-variant-*` property.

Or... **remove the utilities altogether** as they are not necessarily in the spirit of applying middle opinionated typographic styles...?

I suppose anyone using it could just remove them if they see fit.

**Comment by clagnut** [comment]
Couldn't get the custom properties route to work fully for some reason. However I have kept the utilities there and just added some combination classes per Roel's suggestion.

**Comment by jaskfla** [comment]
For what it’s worth, I had some luck with custom properties (tested in WebKit):

```css
:root {
  /* For some reason, not explicitly defining these empty initial values fails */
  --tabular-nums: ;
  --slashed-zero: ;
}
* { font-variant-numeric: var(--tabular-nums) var(--slashed-zero); }
.tnum { --tabular-nums: tabular-nums; }
.zero { --slashed-zero: slashed-zero; }
```

I suspect that the empty values are required because leaving them undefined is—according to [this part of Lea Verou’s recent CSS Day talk](https://youtu.be/ZuZizqDF4q8?si=qPq9n7KO3EQLNGf_&t=1428)[^timestamped]—equivalent to…

[^timestamped]: Timestamped link to around 0:23:48

```css
:root {
  --tabular-nums: initial;
  --slashed-zero: initial;
}
```

…and that presumably expands to an invalid value for `font-variant-numeric`.

### Live demo

👉 [**CodePen demo with Inter** (which has tabular, proportional, slashed and non-slashed)](https://codepen.io/jasperlai/pen/WNVvPEz)
